### ISSUE TITLE
openbis  doit in minimum working example not working on local machine

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/LebeDigital#157]
When running the minimum working example on my local machine, the doit scripts does not run with the error message
```
TaskError - taskid:create_openbis_types:create_mixture_union_yaml
PythonAction Error
Traceback (most recent call last):
  File "/home/junger/github/LebeDigital/conda-env/lib/python3.9/site-packages/doit/action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/junger/github/LebeDigital/usecases/MinimumWorkingExample/upload_scripts/doit_create_types.py", line 25, in create_required_sample_types
    _create_logfiles(mixture_sample_type='RAN ON ACTIONS',
TypeError: _create_logfiles() missing 1 required positional argument: 'ingredient_sample_type'
```

**Comment by cezary17** [comment]
The issue seems to be that I forgot to update a function signature after changing the upload script to make ingredients from the mixture.yaml files. Could you message here the doit function with arguments you set so I can replicate the issue myself?

**Comment by joergfunger** [comment]
This is the main branch, I have not changed anything there.

**Comment by eriktamsen** [comment]
I have the same issue. I do not call any argument to run the dodo, so just run `doit`

**Comment by cezary17** [comment]
I've opened a PR, if you could merge it then the issue should be solved.
