### ISSUE TITLE
tests not running

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/LebeDigital#158]
When running the tests in main, the actions fail with an error
```
ERROR demonstrator_scripts/test_kpi_from_fem.py - AttributeError: module 'pint.compat' has no attribute 'upcast_types'
```

**Comment by eriktamsen** [comment]
It has been like this since Thursday. I was hoping this will resolve itself, looks like a dependency of one of our dependencies has introduced this.
I will try to fix it now.
