### ISSUE TITLE
Modularization and testing

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/LebeDigital#16]
The current structure is not testable. I would suggest decomposing all steps in our workflow into individual modules (essentially functions that take some input and generate some output). These should go be placed into individual folders and should be tested separately. The pydoit workflow would then by an integration test that uses these individual modules. Note that this integration test should include the dpendencies and targets (maybe that is the best thing to start with, since that is essentially the definition of the interfaces of the individual modules.

**Comment by eriktamsen** [comment]
Can we close this issue?
Although the complete thing is not yet running, currently all working steps are modular and being tested.

**Comment by joergfunger** [comment]
We could probably close that issue since we are working on it iteratively and have at least started.
