### ISSUE TITLE
Ignoring precision in integral metadata compiled using quadrature representation. Not implemented.

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/LebeDigital#168]
There is a warning from fenics when running the tests multiple times, could we get rid of that?

**Comment by eriktamsen** [comment]
@joergfunger: I have no idea how to get rid of the message. I have tried for way to long to fix it by including:
```
import warnings
from ffc.quadrature.deprecation import QuadratureRepresentationDeprecationWarning 
warnings.simplefilter("ignore", QuadratureRepresentationDeprecationWarning)
```
in every script that might be responsible, both in `fenics_concrete` as well as here.
Any ideas what else to do? Or should we just live with it and wait to upgrade to fenicsX, which does not have this "feature".

**Comment by joergfunger** [comment]
Yes, if that is not possibleto be solved easily and with a reasonable amount of time, it is not high priority and will be solved anyway as soon as we change to FEniCSx
