### ISSUE TITLE
Calibration test fail randombly

### ISSUE THREAD

**Issue by eriktamsen** [BAMresearch/LebeDigital#184]
The calibration test fails randombly.
Either we need to implement a seed value for the random generator (according to Atul that is not working), or we can only test that there is a result and not care about the value.
The current version with checking the value with a 20% uncertainty that still sometimes fails is not good.

**Comment by joergfunger** [comment]
@atulag0711 Why is that not working with a seed, e.g. [here ](https://github.com/BAMresearch/probeye/blob/1d653933c2c3f964b61257a605a85367147f49d8/tests/integration_tests/tests_with_correlation/test_1D_1D_correlation_additive_model_error_1std.py#L192)?

**Comment by atulag0711** [comment]
> @atulag0711 Why is that not working with a seed, e.g. [here ](https://github.com/BAMresearch/probeye/blob/1d653933c2c3f964b61257a605a85367147f49d8/tests/integration_tests/tests_with_correlation/test_1D_1D_correlation_additive_model_error_1std.py#L192)?

Yes my bad. added two lines, works now. Please approve the PR.

**Comment by eriktamsen** [comment]
I think you need to move the line to the test file.
