### ISSUE TITLE
shacl validation is failing

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/LebeDigital#195]
The tests for the shacl validation are failing. It seems that there are some modifications in some packages. Any (fast) idea @horstf  what is going wrong?

**Comment by horstf** [comment]
I didnt test this, but since rdflib is mentioned in the error output and because v7 was released last week - when the errors started occuring - i suspect that the new version breaks compatibility with pyshacl, which does not seem to be actively maintained anymore. I would suggest pinning rdflib v6 and trying again.

**Comment by joergfunger** [comment]
Thanks for pointing that out. There are now tow options, either pinning rdflib to an old version, or removing the tests that are using pyshacl (since the latter are not yet integrated into the workflow). The first option would allow us to keep the shacl implementation and integrate that into the workflow as soon as the complete graph is build, though with a potentially outdated rdflib package. The second option would require a reimplementation of shacl using a different package (instead of pyshacl), not sure myself what alternatives there are or see if at some later stage it is actually adapted to work with rdflib v7. Any suggestions, in particular @AidaZt ?

**Comment by joergfunger** [comment]
@AidaZt Uncommenting the shacl test files would only work if we also delete the files in LebeDigital, since otherwise the test score (percentage of what is tested) is decreasing, which is not allowed (or we would have to change that too). The easiest solution is (as recommended by @horstf as well), to pin rdflib to version 6.3.2. In my setup, that worked.
