### ISSUE TITLE
Correction of raw mixture data excel files

### ISSUE THREAD

**Issue by alFrie** [BAMresearch/LebeDigital#64]
Some of the raw mixture datafiles (excel) contain spelling mistakes within the labels (like "Wssr" instead of "Wasser"). I want to correct them so that my mixture metadata extraction script can work on them.
My correction should then be approved by @JulietteWinkler.

**Comment by JulietteWinkler** [comment]
The corrections are fine, thank you. 
I'm not sure how to handle the last file. For now I think it's best to exclude it, but we should have in mind that there are files with other layouts (e.g. from KIT or other institutes/labs). I will discuss this problem with Stephan and the other project partners.
