### ISSUE TITLE
Mapping script for mixture metadata

### ISSUE THREAD

**Issue by alFrie** [BAMresearch/LebeDigital#71]
I'm writing the mapping script for the MixOntology.drawio based on the emodule mapping script written by Ilias.

**Comment by joergfunger** [comment]
Not sure if the relevant people are actually reading the issues here. Maybe you have to ask the ontology group directly.

**Comment by joergfunger** [comment]
Btw, the ontologies are also supposed to be in lebedigital/ontologies, not in usecase.

**Comment by joergfunger** [comment]
The folder should already exist (ConcreteOntology).

**Comment by eriktamsen** [comment]
To me, that sounds like a good plan.
Currently in branch #87 the ontologies are in lebedigital/ConcreteOntology, I would suggest to use the same within this branch.
