### ISSUE TITLE
Requested changes for the metadata extraction script

### ISSUE THREAD

**Issue by alFrie** [BAMresearch/LebeDigital#72]
I heard that @joergfunger requested changes:

1. replacing "logger.warning" with "logger.error"
2. including the mixdesign in the script

**Comment by joergfunger** [comment]
Hi Alina,
to change the logger.warning to error would be great, because we don't want to process data that has errors, at least basic information on what is the cement content, .. is required. As for the mix design, this would be a separate task/script.

**Comment by joergfunger** [comment]
Sorry, there are two things mixed up. One (separate) task is the creation of the mix meta data (see above). Another is the integration of the mix into the Youngs' modulus test. This is a single line in the meta data (but the Youngs modulus, not the mix) referencing, what mix has been used for the Young's modulus test. As for the warnings/error yes.

**Comment by joergfunger** [comment]
Could you use the loguru.exception ?

**Comment by joergfunger** [comment]
there seems also the catch option to define whether an exception is automatically catched (thus not propagated to the caller) or if it finishes with an exception.

**Comment by eriktamsen** [comment]
As Jörg is currently on vacation, I will try to guess what he prefers, so you dont have to wait two weeks for an answer. However, no garantee that this is the correct answer.
I personally would suggest the second option. I think currently it might be more imporant to have at least one dataset that is working, with which we can test the whole workflow, than having to make sure that all datasets are working.
Step by step we can then decide what to do with incomplete data or files that have a different format.

**Comment by joergfunger** [comment]
Sorry for my late response, I was on vacation. I agree with Erik, that we would like to make at least one data set working. However, I think this might not work when the script continuous without producing a correct result (because the subsequent processes in the workflow might get inputs that they cannot process). I would then rather change the loop over the raw data files in pydoit (excluding the ones that do not work).
