### ISSUE TITLE
Conda and windows

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/LebeDigital#76]
Our current approach does not allow windows users to install our conda environment since fenics is missing (and there is also no version of fenics available for windows). There are now multiple solutions on howto handle that. 
Option 1: We have a conda environment without fenics and in all test files check of fenics is actually required (if so we would just skip those). This option has the advantage that anyone working only on the extraction and mapping part can still use the library (but cannot test the complete workflow). 
Option 2: We require the windows users to use the windows subsystem (not sure if this is working, having not tested it myself) or use a virtual machine at least at BAM provided by the general IT. What would be the prefered option?

**Comment by eriktamsen** [comment]
Well, I personally would perfere option 2, because that would mean less work for us and I am not programming on Windows.
However the question is, why do we want to run this on Windows. Are there partners that would be developing parts of the workflow, who only use Windows? Have they tried the subsystem?
There would also be an option 3: to move away from doit and use sankemake in the minimum working example. Then we can define environments for each module and I guess people can just run the modules that they require?

**Comment by joergfunger** [comment]
There are partners (in particular @AidaZt ) who is coding in windows. Maybe @AidaZt could try the windows subsystem and see if it is working. Option 3 would also not allow to run the complete tests, which is also suboptimal (we could in theory also rpovide to environment files and only run tests that are supported, but not sure if this is what we would like to do).

**Comment by joergfunger** [comment]
So could you try using the windows subsystem with testing the complete functionality with doit for the usecases and pytest in the test folder?

**Comment by joergfunger** [comment]
That would be possible, but would require the windows users to work with the remote virtual machines. They should comment on whether this is an option.

**Comment by AidaZt** [comment]
yes, virtual Linux machines also can be an option.

**Comment by joergfunger** [comment]
are you talking to the IT to get that. You can talk to our IT.

**Comment by AidaZt** [comment]
I wrote Sebastian, he said WSL is not allowed in the BAM Network but he would create a virtual machine for me.

**Comment by joergfunger** [comment]
What is the status, is that resolved @AidaZt @soudehMasoudian and we can stick to the current approach or do we have to think about changing the code to not exclude windows users from testing the code (since testfiles and conda environments are not working)?

**Comment by AidaZt** [comment]
I have a virtual Linux machine now. Sebastian created that for me.
