### ISSUE TITLE
connect Lebedigital to fuseki server in order to fetch and store dataset through the server

### ISSUE THREAD

**Issue by soudehMasoudian** [BAMresearch/LebeDigital#78]

**Comment by joergfunger** [comment]
How do you intend to integrate that (in particular since everything is now in the CI, you would have to access the triple store in the github actions).

**Comment by soudehMasoudian** [comment]
@joergfunger You are right. we need a mechanism to store generated data by the workflow runs. Do you have any suggestion?

**Comment by joergfunger** [comment]
The triple store is not my expertise at all, maybe talk to Thilo or Andre, how we intend to integrate that. We just have to make sure that at least the tests are still running and integrated.
