### ISSUE TITLE
Initialization of opimization paper

### ISSUE THREAD

**Issue by eriktamsen** [BAMresearch/LebeDigital#83]
Creating proposal for initial structure and workflow setups etc. for planned optimization paper

**Comment by joergfunger** [comment]
just a question, how are we planning to do that  (I'm fine with both options)
a) direct integration into lebedigital as a usecase
b) separate integration that requires the lebedigital package to be installed as external package, but has all the rest separated?
c) starting with a) and planning to move to b) (in particular when there are no more substantial changes in the computations (when the focus is on the actual writing)

**Comment by eriktamsen** [comment]
I assumed a) but I am open for suggestions. I am not sure how b) would look like. what do you mean with "separate integration"?

**Comment by joergfunger** [comment]
b) would be a separate repository that includes the general methods developed in LebeDigital by installing LebeDigital. If the methods are implemented, you just install (via pip or conda) LebeDigital. At some point that would be the idea with the separation of the usecases (which is in the longterm not part of the package) and the module and tests.

**Comment by eriktamsen** [comment]
Then I would suggest a) or c), if at some point we fell it necessary.
My reason to keep it in the repository (for now), is that we are still working on the code, making testing and integrating new changes easier.
I am not sure what the advantage of the seperate repo would be.

**Comment by joergfunger** [comment]
The advantage of a separate repo is only that we do not clutter the original repo with things that are not relevant and in addition the second repo does not necessarily has to be public (e.g. before publishing the paper).
